const data = [
  {
    catergory: "mobile",
    name: "OnePlus Nord CE 3 Lite 5G 256 GB, 8 GB RAM, Pastel Lime, Mobile Phone",
    price: "21,999",
    description:
      "More watts. More battery. More fun. Cram more fun into your day with 67W SUPERVOOC fast charging that gets the hefty 5,000mAh battery up to one days power in just 30 minutes. More zoom, please! Telephoto lens, shmelephoto lens! Who needs telephoto lenses when your main camera has 3? lossless zoom? Get up close and personal with your subjects for vivid details and blur-free photos Pump up the volume Hear all your alerts and leave your portable speakers at home with 200% Ultra Volume Mode. Make your favorite audio as live and loud as you want it to be",
    rating: "5",
    image:
      "https://lh3.googleusercontent.com/spp/ABYooDpkUyyB042KsOKHpsq39LuUfIH1FYC0X4mCBRO_-VPVvP-U-5sCpkJ8A7C9AcNgEjs5et7hKv2GSRGSMso1vdvcTQaD1nE65QfsQY0i4n4UbtAdLrUINhJaTdL8bzPRXKPw3v5TZOp9sEny-merMXWrxuw7rwERlUu17e4Ycg1iR6UTo_CA3FBKyTTkuEcMBGkYBscCeTw=s512-rw-pd-pc0x00ffffff",
    id: 1,
  },
  {
    catergory: "mobile",
    name: "OnePlus Nord CE 2 Lite 5G,128 GB,6 GB RAM,Blue Tide,Mobile Phone",
    price: "16,999",
    description: "Big 120Hz display = more battery life Youd think a big 16.73cm (6.59?) 120Hz display? would put a huge dent in your battery life. But Nord CE 2 Lites display is an energy-saving LCD. That means more time for watching your favourite shows in FHD + resolution.",
    rating: "4.5",
    image: "https://lh3.googleusercontent.com/spp/ABYooDowZHLyGVYvFHAVhUAAG2llDbs97cCsItsfEzPmhptsvQXGFO9HkEuUFbFXSC-jg-Q0ZYk8p87ljWFC5lw-WC0eOA_Ag7C2vgIdPW66zF9SZD6nG8KDZrHYu54BBiJ5EU88dcWmImwhobLAI6tL7ahiJHSfj-7ST_MoYPkyE-i2y5Mc8dTz4CO8VqGDZcfVlFWl-Vfn=s512-rw-pd-pc0x00ffffff",
    id: 2,
  },
  {
    catergory: "mobile",
    name: "OnePlus Nord CE3 5G 256GB, 12GB RAM, Aqua Surge",
    price: "27,999",
    description: "17.01 cm (6.7 Inch),12 GB RAM 256 GB ROM,Qualcomm Snapdragon 782G,OxygenOS based on Android 13.1,50MP + 8MP + 2MP Rear Camera,16MP Selfie Camera,5000 mAh Battery and more in the OnePlus Nord CE3 5G 256GB, 12GB RAM, Aqua Surge, Mobile Phone",
    rating: "4.9",
    image: "https://lh3.googleusercontent.com/spp/ABYooDpHqOi894pkQkTpIpCYLJvEt9bHDt-vx-RMa6CbMwAbdKwlNrCqbF44x67FpDDUfugiDkc3zU8b0qXyeKhDjIF5zBTbUI71Ghu7su8ys0Lvl3jv9i1Q_i5DSq0g3Y-rJK0AQa-l2w0OZ6lgK9OdBBOSy_zlC69R2BrOPl1aXWJMHvANvi1sKs7OaMXEYCwO3JJr5pNKIKg=s512-rw-pd-pc0x00ffffff",
    id:3,
  },
  {
    catergory: "mobile",
    name: "OnePlus 11 5G 256 GB, 16 GB Ram, Eternal Green, Mobile Phone",
    price: "61,999",
    description: "	Data cable (USB-A to USB Type-C), Charger (SuperVOOC 100 Watt), SIM ejector tool, Protective case, Quick Guide, Safety Guide, Brand sticker, Side hole sticker, Welcome Letter",
    rating: "4.3",
    image: "https://www.jiomart.com/images/product/original/493665045/oneplus-11-5g-256-gb-16-gb-ram-eternal-green-mobile-phone-digital-o493665045-p598159053-0-202302081921.jpeg?im=Resize=(420,420)",
    id: 4,
  },
  {
    catergory: "mobile",
    name: "OnePlus Ace Racing Edition 5G ",
    price: "22,990",
    description: "OnePlus Ace Racing Edition 5G expected price in India starts from ₹22,990. Take a look at OnePlus Ace Racing Edition 5G detailed specifications and features.",
    rating: "4",
    image: "https://cdn1.smartprix.com/rx-i0WlpU3oE-w1200-h1200/0WlpU3oE.jpg",
    id: 5,
  },
  {
    catergory: "mobile",
    name: "OnePlus Nord CE3 5G 256GB, 12GB RAM, Grey Shimmer, Mobile Phone    ",
    price: "27,999",
    description: "17.01 cm (6.7 Inch),12 GB RAM 256 GB ROM,Qualcomm Snapdragon 782G,OxygenOS based on Android 13.1,50MP + 8MP + 2MP Rear Camera,16MP Selfie Camera,5000 mAh Battery and more in the OnePlus Nord CE3 5G 256GB, 12GB RAM, Grey Shimmer, Mobile Phone    ",
    rating: "3.8",
    image: "https://lh3.googleusercontent.com/spp/ABYooDqA4ZpPya2ealGq3Yr8zKPasrLpMw0Qz-21G3NBefT0mtpeSItKjleEd9jm2UzLzwCfobs6Ks-6IxW885MA7trQV2Pi2zzZRjCzbwO37BvInfvLswrlFwr_gr3CfqcN-zX7HMCHSKAopheSWsSbxyReYzUtsYKhFr3KeD8jMCBGsuxVt7ytyeLRQbtxtIxN6UjaUTRtFw=s512-rw-pd-pc0x00ffffff",
    id: 6,
  },
  {
    catergory: "mobile",
    name: "OnePlus Nord CE 3 Lite 5G 256 GB, 8 GB RAM, Pastel Lime, Mobile Phone",
    price: "21,999",
    description: "	 67 Watt SUPERVOOC Charger OxygensOS 13.1 Operating System Up to 8 GB Virtual RAM Expansion 3x Lossless Zoom Electronic Image Stabilization (EIS) Dual Stereo Speakers Noise cancellation support 200 Percent Ultra Volume Mode Touch Response Rate: 240Hz Eye comfort",
    rating: "4.1",
    image: "https://www.jiomart.com/images/product/original/493665925/oneplus-nord-ce-3-lite-5g-256-gb-8-gb-ram-pastel-lime-mobile-phone-digital-o493665925-p600340967-0-202304101447.jpeg?im=Resize=(420,420)",
    id: 7,
  },
  {
    catergory: "mobile",
    name: "iPhone 15",
    price: "79,900",
    description: "As part of our efforts to reach carbon neutrality by 2030, iPhone 15 and iPhone 15 Plus do not include a power adapter or EarPods. Included in the box is a USB‑C Charge Cable that supports fast charging and is compatible with USB‑C power adapters and computer ports.    ",
    rating: "4.5",
    image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-blue?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1692923777972",
    id: 8,
  },
  {
    catergory: "mobile",
    name: "iPhone 14",
    price: "69,900",
    description: "As part of our efforts to reach carbon neutrality by 2030, iPhone 14 and iPhone 14 Plus do not include a power adapter or EarPods",
    rating: "4.2",
    image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-14-storage-select-202209-6-1inch-blue?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1660691647109",
    id: 9,
  },
  {
    catergory: "mobile",
    name: "iPhone 13",
    price: "59,900",
    description: "As part of our efforts to reach carbon neutrality by 2030, iPhone 13 does not include a power adapter or EarPods",
    rating: "4.3",
    image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-storage-select-202207-blue?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1693064358917",
    id: 10,
  },
  {
    catergory: "mobile",
    name: "iPhone 15 Pro",
    price: "159,900",
    description: "As part of our efforts to reach carbon neutrality by 2030, iPhone 15 Pro and iPhone 15 Pro Max do not include a power adapter or EarPods. Included in the box is a USB‑C Charge Cable that supports fast charging and is compatible with USB‑C power adapters and computer ports.",
    rating: "5",
    image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-7inch-naturaltitanium?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1692845702708",
    id: 11,
  },
  {
    catergory: "mobile",
    name: "iPhone 15 Pro",
    price: "134,900",
    description: "As part of our efforts to reach carbon neutrality by 2030, iPhone 15 Pro and iPhone 15 Pro Max do not include a power adapter or EarPods. Included in the box is a USB‑C Charge Cable that supports fast charging and is compatible with USB‑C power adapters and computer ports.    ",
    rating: "4.9",
    image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-bluetitanium?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1692846360609",
    id: 12,
  },
  {
    catergory: "mobile",
    name: "Samsung Galaxy F13",
    price: "13,999",
    description: " Estimated against the usage profile of an average/typical user. Independently assessed by Strategy Analytics between 2021.12.08–12.20 in USA and UK with pre-release versions of SM-S901, SM-S906, SM-S908 under default setting using 5G Sub6 networks (NOT tested under 5G mmWave network). ",
    rating: "4.6",
    image: "https://images.samsung.com/is/image/samsung/p6pim/in/sm-e135fzggins/gallery/in-galaxy-f13-sm-e135fzggins-532859820?$1300_1038_PNG$",
    id: 13,
  },
  {
    catergory: "mobile",
    name: "",
    price: "",
    description: "",
    rating: "",
    image: "",
    id: 14,
  },
  {
    catergory: "mobile",
    name: "",
    price: "",
    description: "",
    rating: "",
    image: "",
    id: 2,
  },
  {
    catergory: "mobile",
    name: "",
    price: "",
    description: "",
    rating: "",
    image: "",
    id: 2,
  },
  {
    catergory: "mobile",
    name: "",
    price: "",
    description: "",
    rating: "",
    image: "",
    id: 2,
  },
];

module.exports=data
